// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysDataLog 数据日志表数据对象
type SysDataLog struct {
	g.Meta      `orm:"table:sys_data_log, do:true"`
	Id          interface{} // 主键
	CreateBy    interface{} // 创建人登录名称
	CreateTime  interface{} // 创建日期
	UpdateBy    interface{} // 更新人登录名称
	UpdateTime  interface{} // 更新日期
	DataTable   interface{} // 表名
	DataId      interface{} // 数据ID
	DataContent interface{} // 数据内容
	DataVersion interface{} // 版本号
}
