// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysFile 系统文件表数据对象
type SysFile struct {
	g.Meta       `orm:"table:sys_file, do:true"`
	Id           interface{} // 主键
	CreateTime   interface{} // 创建日期
	UpdateBy     interface{} // 更新人
	CreateBy     interface{} // 创建人
	UpdateTime   interface{} // 更新日期
	SysOrgCode   interface{} // 所属部门
	FileType     interface{} // 文件类型
	FileName     interface{} // 文件名
	FilePath     interface{} // 文件路径
	FileLocation interface{} // 存储位置
	FileTag      interface{} // 文件标签
	DelFlag      interface{} // 是否删除
}
