// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysLog 系统日志表数据对象
type SysLog struct {
	g.Meta       `orm:"table:sys_log, do:true"`
	Id           interface{} // 主键
	LogType      interface{} // 日志类型（1登录日志，2操作日志）
	LogContent   interface{} // 日志内容
	OperateType  interface{} // 操作类型
	Userid       interface{} // 操作用户账号
	Username     interface{} // 操作用户名称
	Ip           interface{} // IP
	Method       interface{} // 请求方法
	RequestUrl   interface{} // 请求路径
	RequestParam interface{} // 请求参数
	RequestType  interface{} // 请求类型
	CostTime     interface{} // 耗时
	CreateBy     interface{} // 创建人
	CreateTime   interface{} // 创建时间
	UpdateBy     interface{} // 更新人
	UpdateTime   interface{} // 更新时间
}
