// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import "github.com/gogf/gf/v2/os/gtime"

// SysDataLog 数据日志表实体
type SysDataLog struct {
	Id          string      `json:"id"`          // 主键
	CreateBy    string      `json:"createBy"`    // 创建人登录名称
	CreateTime  *gtime.Time `json:"createTime"`  // 创建日期
	UpdateBy    string      `json:"updateBy"`    // 更新人登录名称
	UpdateTime  *gtime.Time `json:"updateTime"`  // 更新日期
	DataTable   string      `json:"dataTable"`   // 表名
	DataId      string      `json:"dataId"`      // 数据ID
	DataContent string      `json:"dataContent"` // 数据内容
	DataVersion int         `json:"dataVersion"` // 版本号
}
