// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import "github.com/gogf/gf/v2/os/gtime"

// SysFile 系统文件表实体
type SysFile struct {
	Id           string      `json:"id"`           // 主键
	CreateTime   *gtime.Time `json:"createTime"`   // 创建日期
	UpdateBy     string      `json:"updateBy"`     // 更新人
	CreateBy     string      `json:"createBy"`     // 创建人
	UpdateTime   *gtime.Time `json:"updateTime"`   // 更新日期
	SysOrgCode   string      `json:"sysOrgCode"`   // 所属部门
	FileType     int         `json:"fileType"`     // 文件类型
	FileName     string      `json:"fileName"`     // 文件名
	FilePath     string      `json:"filePath"`     // 文件路径
	FileLocation int         `json:"fileLocation"` // 存储位置 1:本地 2:阿里云 3:七牛云
	FileTag      string      `json:"fileTag"`      // 文件标签
	DelFlag      int         `json:"delFlag"`      // 是否删除
}
