// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import "github.com/gogf/gf/v2/os/gtime"

// SysLog 系统日志表实体
type SysLog struct {
	Id           string      `json:"id"`           // 主键
	LogType      int         `json:"logType"`      // 日志类型（1登录日志，2操作日志）
	LogContent   string      `json:"logContent"`   // 日志内容
	OperateType  int         `json:"operateType"`  // 操作类型
	Userid       string      `json:"userid"`       // 操作用户账号
	Username     string      `json:"username"`     // 操作用户名称
	Ip           string      `json:"ip"`           // IP
	Method       string      `json:"method"`       // 请求方法
	RequestUrl   string      `json:"requestUrl"`   // 请求路径
	RequestParam string      `json:"requestParam"` // 请求参数
	RequestType  string      `json:"requestType"`  // 请求类型
	CostTime     int64       `json:"costTime"`     // 耗时
	CreateBy     string      `json:"createBy"`     // 创建人
	CreateTime   *gtime.Time `json:"createTime"`   // 创建时间
	UpdateBy     string      `json:"updateBy"`     // 更新人
	UpdateTime   *gtime.Time `json:"updateTime"`   // 更新时间
}
