// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingWorkDao is internal type for wrapping internal DAO implements.
type internalTeachingWorkDao = *internal.TeachingWorkDao

// teachingWorkDao is the data access object for table teaching_work.
// You can define custom methods on it to extend its functionality as you wish.
type teachingWorkDao struct {
	internalTeachingWorkDao
}

var (
	// TeachingWork is globally accessible object for table teaching_work operations.
	TeachingWork = teachingWorkDao{
		internal.NewTeachingWorkDao(),
	}
)

// Fill with your custom methods below.