// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

type internalTeachingCourseDeptDao = *internal.TeachingCourseDeptDao

type teachingCourseDeptDao struct {
	internalTeachingCourseDeptDao
}

var (
	TeachingCourseDept = teachingCourseDeptDao{
		internal.NewTeachingCourseDeptDao(),
	}
)
