// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingScratchAssetDao is internal type for wrapping internal DAO implements.
type internalTeachingScratchAssetDao = *internal.TeachingScratchAssetDao

// teachingScratchAssetDao is the data access object for table teaching_scratch_assets.
// You can define custom methods on it to extend its functionality as you wish.
type teachingScratchAssetDao struct {
	internalTeachingScratchAssetDao
}

var (
	// TeachingScratchAsset is globally public accessible object for table teaching_scratch_assets operations.
	TeachingScratchAsset = teachingScratchAssetDao{
		internal.NewTeachingScratchAssetDao(),
	}
)

// Fill with you ideas below.
