// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingWorkCommentDao is internal type for wrapping internal DAO implements.
type internalTeachingWorkCommentDao = *internal.TeachingWorkCommentDao

// teachingWorkCommentDao is the data access object for table teaching_work_comment.
// You can define custom methods on it to extend its functionality as you wish.
type teachingWorkCommentDao struct {
	internalTeachingWorkCommentDao
}

var (
	// TeachingWorkComment is globally accessible object for table teaching_work_comment operations.
	TeachingWorkComment = teachingWorkCommentDao{
		internal.NewTeachingWorkCommentDao(),
	}
)

// Fill with your custom methods below.