// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingNewsDao is internal type for wrapping internal DAO implements.
type internalTeachingNewsDao = *internal.TeachingNewsDao

// teachingNewsDao is the data access object for table teaching_news.
// You can define custom methods on it to extend its functionality as you wish.
type teachingNewsDao struct {
	internalTeachingNewsDao
}

var (
	// TeachingNews is globally accessible object for table teaching_news operations.
	TeachingNews = teachingNewsDao{
		internal.NewTeachingNewsDao(),
	}
)

// Fill with your custom methods below.
