// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingWorkCorrectDao is internal type for wrapping internal DAO implements.
type internalTeachingWorkCorrectDao = *internal.TeachingWorkCorrectDao

// teachingWorkCorrectDao is the data access object for table teaching_work_correct.
// You can define custom methods on it to extend its functionality as you wish.
type teachingWorkCorrectDao struct {
	internalTeachingWorkCorrectDao
}

var (
	// TeachingWorkCorrect is globally accessible object for table teaching_work_correct operations.
	TeachingWorkCorrect = teachingWorkCorrectDao{
		internal.NewTeachingWorkCorrectDao(),
	}
)

// Fill with your custom methods below.