// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysDataLogDao is the data access object for table sys_data_log.
type SysDataLogDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns SysDataLogColumns // columns contains all the column names of Table for convenient usage.
}

// SysDataLogColumns defines and stores column names for table sys_data_log.
type SysDataLogColumns struct {
	Id          string // 主键
	CreateBy    string // 创建人登录名称
	CreateTime  string // 创建日期
	UpdateBy    string // 更新人登录名称
	UpdateTime  string // 更新日期
	DataTable   string // 表名
	DataId      string // 数据ID
	DataContent string // 数据内容
	DataVersion string // 版本号
}

// sysDataLogColumns holds the columns for table sys_data_log.
var sysDataLogColumns = SysDataLogColumns{
	Id:          "id",
	CreateBy:    "create_by",
	CreateTime:  "create_time",
	UpdateBy:    "update_by",
	UpdateTime:  "update_time",
	DataTable:   "data_table",
	DataId:      "data_id",
	DataContent: "data_content",
	DataVersion: "data_version",
}

// NewSysDataLogDao creates and returns a new DAO object for table data access.
func NewSysDataLogDao() *SysDataLogDao {
	return &SysDataLogDao{
		group:   "default",
		table:   "sys_data_log",
		columns: sysDataLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysDataLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysDataLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysDataLogDao) Columns() SysDataLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysDataLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysDataLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
func (dao *SysDataLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
