// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysLogDao is the data access object for table sys_log.
type SysLogDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns SysLogColumns // columns contains all the column names of Table for convenient usage.
}

// SysLogColumns defines and stores column names for table sys_log.
type SysLogColumns struct {
	Id           string // 主键
	LogType      string // 日志类型（1登录日志，2操作日志）
	LogContent   string // 日志内容
	OperateType  string // 操作类型
	Userid       string // 操作用户账号
	Username     string // 操作用户名称
	Ip           string // IP
	Method       string // 请求方法
	RequestUrl   string // 请求路径
	RequestParam string // 请求参数
	RequestType  string // 请求类型
	CostTime     string // 耗时
	CreateBy     string // 创建人
	CreateTime   string // 创建时间
	UpdateBy     string // 更新人
	UpdateTime   string // 更新时间
}

// sysLogColumns holds the columns for table sys_log.
var sysLogColumns = SysLogColumns{
	Id:           "id",
	LogType:      "log_type",
	LogContent:   "log_content",
	OperateType:  "operate_type",
	Userid:       "userid",
	Username:     "username",
	Ip:           "ip",
	Method:       "method",
	RequestUrl:   "request_url",
	RequestParam: "request_param",
	RequestType:  "request_type",
	CostTime:     "cost_time",
	CreateBy:     "create_by",
	CreateTime:   "create_time",
	UpdateBy:     "update_by",
	UpdateTime:   "update_time",
}

// NewSysLogDao creates and returns a new DAO object for table data access.
func NewSysLogDao() *SysLogDao {
	return &SysLogDao{
		group:   "default",
		table:   "sys_log",
		columns: sysLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysLogDao) Columns() SysLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
func (dao *SysLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
