// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysDictDao is internal type for wrapping internal DAO implements.
type internalSysDictDao = *internal.SysDictDao

// sysDictDao is the data access object for table sys_dict.
type sysDictDao struct {
	internalSysDictDao
}

var (
	// SysDict is globally public accessible object for table sys_dict operations.
	SysDict = sysDictDao{
		internal.NewSysDictDao(),
	}
)
