// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysDictItemDao is internal type for wrapping internal DAO implements.
type internalSysDictItemDao = *internal.SysDictItemDao

// sysDictItemDao is the data access object for table sys_dict_item.
type sysDictItemDao struct {
	internalSysDictItemDao
}

var (
	// SysDictItem is globally public accessible object for table sys_dict_item operations.
	SysDictItem = sysDictItemDao{
		internal.NewSysDictItemDao(),
	}
)
