// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysRolePermissionDao is internal type for wrapping internal DAO implements.
type internalSysRolePermissionDao = *internal.SysRolePermissionDao

// sysRolePermissionDao is the data access object for table sys_role_permission.
// You can define custom methods on it to extend its functionality as you wish.
type sysRolePermissionDao struct {
	internalSysRolePermissionDao
}

var (
	// SysRolePermission is globally public accessible object for table sys_role_permission operations.
	SysRolePermission = sysRolePermissionDao{
		internal.NewSysRolePermissionDao(),
	}
)

// Fill with you ideas below.
