// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysDataLogDao is internal type for wrapping internal DAO implements.
type internalSysDataLogDao = *internal.SysDataLogDao

// sysDataLogDao is the data access object for table sys_data_log.
// You can define custom methods on it to extend its functionality as you wish.
type sysDataLogDao struct {
	internalSysDataLogDao
}

var (
	// SysDataLog is globally public accessible object for table sys_data_log operations.
	SysDataLog = sysDataLogDao{
		internal.NewSysDataLogDao(),
	}
)
