// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysDepartDao is internal type for wrapping internal DAO implements.
type internalSysDepartDao = *internal.SysDepartDao

// sysDepartDao is the data access object for table sys_depart.
// You can define custom methods on it to extend its functionality as you wish.
type sysDepartDao struct {
	internalSysDepartDao
}

var (
	// SysDepart is globally public accessible object for table sys_depart operations.
	SysDepart = sysDepartDao{
		internal.NewSysDepartDao(),
	}
)
