// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalSysUserDepartDao is internal type for wrapping internal DAO implements.
type internalSysUserDepartDao = *internal.SysUserDepartDao

// sysUserDepartDao is the data access object for table sys_user_depart.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserDepartDao struct {
	internalSysUserDepartDao
}

var (
	// SysUserDepart is globally public accessible object for table sys_user_depart operations.
	SysUserDepart = sysUserDepartDao{
		internal.NewSysUserDepartDao(),
	}
)
