// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

type internalTeachingCourseUnitDao = *internal.TeachingCourseUnitDao

type teachingCourseUnitDao struct {
	internalTeachingCourseUnitDao
}

var (
	TeachingCourseUnit = teachingCourseUnitDao{
		internal.NewTeachingCourseUnitDao(),
	}
)