// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingCourseDao is internal type for wrapping internal DAO implements.
type internalTeachingCourseDao = *internal.TeachingCourseDao

// teachingCourseDao is the data access object for table teaching_course.
// You can define custom methods on it to extend its functionality as you wish.
type teachingCourseDao struct {
	internalTeachingCourseDao
}

var (
	// TeachingCourse is globally public accessible object for table teaching_course operations.
	TeachingCourse = teachingCourseDao{
		internal.NewTeachingCourseDao(),
	}
)

// Fill with you ideas below.
