// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"teaching-open/internal/dao/internal"
)

// internalTeachingDepartDayLogDao is internal type for wrapping internal DAO implements.
type internalTeachingDepartDayLogDao = *internal.TeachingDepartDayLogDao

// teachingDepartDayLogDao is the data access object for table teaching_depart_day_log.
// You can define custom methods on it to extend its functionality as you wish.
type teachingDepartDayLogDao struct {
	internalTeachingDepartDayLogDao
}

var (
	// TeachingDepartDayLog is globally public accessible object for table teaching_depart_day_log operations.
	TeachingDepartDayLog = teachingDepartDayLogDao{
		internal.NewTeachingDepartDayLogDao(),
	}
)

// Fill with you ideas below.
